module Riaque
  module Document

    def self.included(base)
      base.extend ClassMethods
    end

    # Override save to provide conflict resolution.
    #
    # @return [Boolean]
    #
    def save
      # Attempt the save.
      #
      result = super

      # Return result of conflict resolution.
      #
      if self.conflict?
        self.jobs = self.siblings.map(&:jobs).flatten.uniq 
        return self.save
      end

      # Otherwise return save result.
      #
      return result
    end

    # Return conflict on save status.
    #
    # @return [Boolean]
    #
    def conflict?
      self.robject.conflict?
    end

    # Returns siblings, in the event of a conflict.
    #
    # @return [Array]
    #
    def siblings
      self.robject.siblings
    end

    module ClassMethods

      # Returns the autogenerated key based on an instances attributes.
      #
      # @param  [Hash]   attributes
      # @return [String] default key for instance
      #
      def default_key(attributes)
        self.new(attributes).default_key
      end

      # Given a set of attributes, attempts to find a object using the
      # autogenerated key.
      #
      # @param  [Hash]   attributes
      # @return [Object] returned object if available, else nil.
      #
      def find_with_attributes(attributes)
        begin 
          self.find(self.default_key(attributes))
        rescue Riak::HTTPFailedRequest 
          nil
        end
      end

      # Given a set of attributes, attempts to find a object using the
      # autogenerated key or creates it otherwise.
      #
      # @param  [Hash]   attributes
      # @return [Object] object.
      #
      def find_or_create_with_attributes(attributes)
        instance = self.new(attributes)

        begin 
          self.find(instance.default_key)
        rescue Riak::HTTPFailedRequest 
          instance
        end
      end

    end

  end
end
